import { auth, db } from './firebase.js';
import { onAuthStateChanged, signInAnonymously } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { addDoc, collection, deleteDoc, doc, endAt, getDoc, getDocs, limit, onSnapshot, orderBy, query, runTransaction, serverTimestamp, setDoc, startAt, updateDoc } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const E={home:$('home'),profileView:$('profileView'),editor:$('editor'),timeline:$('timeline'),mine:$('mine'),status:$('status'),profile:$('profile'),new:$('new'),ver:$('ver'),update:$('update'),type:$('type'),title:$('title'),titleLabel:$('titleLabel'),suggestions:$('suggestions'),stars:$('stars'),ratingText:$('ratingText'),options:$('options'),note:$('note'),save:$('save'),cancelEdit:$('cancelEdit'),editorTitle:$('editorTitle'),error:$('error'),toast:$('toast'),modal:$('modal'),cancelDelete:$('cancelDelete'),doDelete:$('doDelete'),profileName:$('profileName'),profileBioText:$('profileBioText'),avatar:$('avatar'),total:$('total'),ramenCount:$('ramenCount'),movieCount:$('movieCount'),editProfile:$('editProfile'),profileForm:$('profileForm'),displayName:$('displayName'),bio:$('bio'),saveProfile:$('saveProfile'),install:$('install'),pickImage:$('pickImage'),imageInput:$('imageInput'),previewWrap:$('previewWrap'),preview:$('preview'),removeImage:$('removeImage'),imageSize:$('imageSize')};
const RAMEN=[['スープ',['醤油','味噌','塩','豚骨','鶏白湯','魚介','家系']],['麺',['細麺','中細麺','中太麺','太麺','ちぢれ麺']],['味の濃さ',['あっさり','ほどよい','濃厚']],['店の雰囲気',['一人向け','家族向け','おしゃれ','活気あり','落ち着く']],['接客',['接客◎','普通','少し気になる']]];
const MOVIE=[['脚本',['脚本◎','分かりやすい','意外性あり','考察向け']],['映像',['映像◎','迫力あり','美しい']],['キャスト',['キャスト◎','演技◎','推し出演']],['音楽',['音楽◎','主題歌◎']],['観終わった気分',['泣ける','笑える','爽快','余韻あり','ハラハラ','ほっこり']]];
const S={user:null,reviews:[],profile:{displayName:'',bio:''},filter:'all',rating:0,tags:[],editId:null,deleteId:null,image:'',installPrompt:null};
function toast(m){E.toast.textContent=m;E.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.add('hidden'),2200)}
function screen(x){[E.home,E.profileView,E.editor].forEach(a=>a.classList.add('hidden'));x.classList.remove('hidden')}
function opts(){const a=E.type.value==='ramen'?RAMEN:MOVIE;E.options.innerHTML=a.map(([n,v])=>`<fieldset><legend>${n}</legend><div class="chips">${v.map(t=>`<button class="chip ${S.tags.includes(t)?'on':''}" data-tag="${t}">${t}</button>`).join('')}</div></fieldset>`).join('')}
function stars(){E.stars.querySelectorAll('button').forEach(b=>b.classList.toggle('on',+b.dataset.n<=S.rating));E.ratingText.textContent=S.rating?`${S.rating} / 5`:'未選択'}
function setType(t){E.type.value=t;document.querySelectorAll('.genre').forEach(b=>b.classList.toggle('on',b.dataset.type===t));E.titleLabel.textContent=t==='ramen'?'店名':'映画タイトル';S.tags=[];opts()}
function date(t){return t?.toDate?new Intl.DateTimeFormat('ja-JP',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(t.toDate()):'たった今'}
function own(r){return r.userId===S.user?.uid}
function card(r){let n=Math.max(0,Math.min(5,+r.rating||0));return `<article class="card"><div class="cardHead"><span class="avatar">${esc((r.displayName||'?')[0])}</span><div class="user"><b>${esc(r.displayName||'ゲスト')}</b><small>${date(r.createdAt)}</small></div><span class="badge">${r.type==='ramen'?'🍜 ラーメン':'🎬 映画'}</span></div><div class="body"><h2>${esc(r.title)}</h2><div class="cardStars">${'★'.repeat(n)}${'☆'.repeat(5-n)}</div>${r.image?`<img class="reviewImage" src="${r.image}" alt="レビュー写真" loading="lazy">`:''}${r.tags?.length?`<div class="tags">${r.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`:''}${r.note?`<p>${esc(r.note)}</p>`:''}${own(r)?`<div class="actions"><button data-share="${r.id}">共有文をコピー</button><button data-edit="${r.id}">編集</button><button class="delete" data-delete="${r.id}">削除</button></div>`:''}</div></article>`}
function render(){let a=S.filter==='all'?S.reviews:S.reviews.filter(r=>r.type===S.filter);E.timeline.innerHTML=a.length?a.map(card).join(''):'<p>まだレビューがありません。</p>'}
function renderProfile(){let a=S.reviews.filter(own),n=S.profile.displayName||'未登録';E.profileName.textContent=n;E.profileBioText.textContent=S.profile.bio||'プロフィールを登録してください';E.avatar.textContent=n[0]||'?';E.total.textContent=a.length;E.ramenCount.textContent=a.filter(r=>r.type==='ramen').length;E.movieCount.textContent=a.filter(r=>r.type==='movie').length;E.mine.innerHTML=a.length?a.map(card).join(''):'<p>自分のレビューはまだありません。</p>'}
function reset(){S.rating=0;S.tags=[];S.editId=null;S.image='';E.title.value='';E.note.value='';E.imageInput.value='';E.previewWrap.classList.add('hidden');E.editorTitle.textContent='レビューを投稿';E.save.textContent='タイムラインに投稿';E.cancelEdit.classList.add('hidden');opts();stars()}
async function image(file){if(!file)return;try{let im=await new Promise((ok,no)=>{let r=new FileReader;r.onload=()=>{let i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=r.result};r.readAsDataURL(file)}),scale=Math.min(1,720/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*scale;c.height=im.height*scale;c.getContext('2d').drawImage(im,0,0,c.width,c.height);let q=.7,d=c.toDataURL('image/jpeg',q),kb=()=>Math.round(d.length*.75/1024);while(kb()>550&&q>.35){q-=.08;d=c.toDataURL('image/jpeg',q)}if(kb()>650)throw Error('画像を小さくできませんでした');S.image=d;E.preview.src=d;E.imageSize.textContent=`約${kb()}KB`;E.previewWrap.classList.remove('hidden');toast('写真を追加しました')}catch(e){console.error(e);toast(e.message||'写真を処理できませんでした')}}
async function master(name){let id=encodeURIComponent(name.toLowerCase()).replaceAll('%','_').replaceAll('/','_').slice(0,700),ref=doc(db,'ramenMasters',id);await runTransaction(db,async tx=>{let s=await tx.get(ref);s.exists()?tx.update(ref,{reviewCount:(s.data().reviewCount||0)+1,updatedAt:serverTimestamp()}):tx.set(ref,{name,reviewCount:1,createdBy:S.user.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})})}
async function save(){let title=E.title.value.trim(),name=S.profile.displayName;if(!name){screen(E.profileView);E.profileForm.classList.remove('hidden');return toast('表示名を登録してください')}if(!title||!S.rating){E.error.textContent='タイトルと星評価は必須です';E.error.classList.remove('hidden');return}let data={type:E.type.value,title,rating:S.rating,tags:S.tags,note:E.note.value.trim(),image:S.image,displayName:name,userId:S.user.uid,updatedAt:serverTimestamp()};try{if(S.editId)await updateDoc(doc(db,'reviews',S.editId),data);else{await addDoc(collection(db,'reviews'),{...data,createdAt:serverTimestamp()});if(data.type==='ramen')await master(title)}reset();screen(E.home);toast('保存しました')}catch(e){console.error(e);E.error.textContent='保存できませんでした';E.error.classList.remove('hidden')}}
function edit(id){let r=S.reviews.find(x=>x.id===id);if(!r||!own(r))return;S.editId=id;setType(r.type);E.title.value=r.title;E.note.value=r.note||'';S.rating=+r.rating;S.tags=[...(r.tags||[])];S.image=r.image||'';if(S.image){E.preview.src=S.image;E.previewWrap.classList.remove('hidden');E.imageSize.textContent=`約${Math.round(S.image.length*.75/1024)}KB`}opts();stars();E.editorTitle.textContent='レビューを編集';E.save.textContent='変更を保存';E.cancelEdit.classList.remove('hidden');screen(E.editor)}
async function copy(id){let r=S.reviews.find(x=>x.id===id);if(!r||!own(r))return;let text=`${r.type==='ramen'?`この前行った「${r.title}」、良かった！`:`「${r.title}」観た！良かった！`}\n評価：${'★'.repeat(r.rating)}${r.tags?.length?`\n良かったところ：${r.tags.join('・')}`:''}${r.note?`\nひとこと：${r.note}`:''}\n\n#KUCHIKOMI\n${location.origin}${location.pathname}`;await navigator.clipboard.writeText(text);toast('共有文をコピーしました')}
async function loadProfile(){let s=await getDoc(doc(db,'users',S.user.uid));if(s.exists())S.profile=s.data();renderProfile()}
async function saveProfile(){let displayName=E.displayName.value.trim(),bio=E.bio.value.trim();if(!displayName)return toast('表示名を入力してください');await setDoc(doc(db,'users',S.user.uid),{displayName,bio,updatedAt:serverTimestamp()},{merge:true});S.profile={displayName,bio};E.profileForm.classList.add('hidden');renderProfile();toast('プロフィールを保存しました')}
function action(e){let b=e.target.closest('button');if(!b)return;if(b.dataset.edit)edit(b.dataset.edit);if(b.dataset.share)copy(b.dataset.share);if(b.dataset.delete){S.deleteId=b.dataset.delete;E.modal.classList.remove('hidden')}}
document.querySelectorAll('.back').forEach(b=>b.onclick=()=>screen(E.home));E.new.onclick=()=>{reset();screen(E.editor)};E.profile.onclick=()=>{renderProfile();screen(E.profileView)};E.editProfile.onclick=()=>{E.displayName.value=S.profile.displayName||'';E.bio.value=S.profile.bio||'';E.profileForm.classList.toggle('hidden')};E.saveProfile.onclick=saveProfile;E.save.onclick=save;E.cancelEdit.onclick=()=>{reset();screen(E.home)};document.querySelectorAll('.genre').forEach(b=>b.onclick=()=>setType(b.dataset.type));document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('on',x===b));render()});E.stars.onclick=e=>{let b=e.target.closest('button');if(b){S.rating=+b.dataset.n;stars()}};E.options.onclick=e=>{let b=e.target.closest('.chip');if(b){S.tags.includes(b.dataset.tag)?S.tags=S.tags.filter(x=>x!==b.dataset.tag):S.tags.push(b.dataset.tag);opts()}};E.pickImage.onclick=()=>E.imageInput.click();E.imageInput.onchange=()=>image(E.imageInput.files[0]);E.removeImage.onclick=()=>{S.image='';E.previewWrap.classList.add('hidden')};E.timeline.onclick=E.mine.onclick=action;E.cancelDelete.onclick=()=>E.modal.classList.add('hidden');E.doDelete.onclick=async()=>{let r=S.reviews.find(x=>x.id===S.deleteId);if(r&&own(r))await deleteDoc(doc(db,'reviews',S.deleteId));E.modal.classList.add('hidden')};E.install.onclick=async()=>{if(S.installPrompt){S.installPrompt.prompt();await S.installPrompt.userChoice}else toast(/iphone|ipad/i.test(navigator.userAgent)?'Safariの共有から「ホーム画面に追加」を選んでください':'ブラウザのメニューからインストールしてください')};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();S.installPrompt=e});E.update.onclick=()=>location.replace(`${location.pathname}?v=1.1.0&t=${Date.now()}`);
onAuthStateChanged(auth,async user=>{if(!user){await signInAnonymously(auth);return}S.user=user;await loadProfile();onSnapshot(query(collection(db,'reviews'),orderBy('createdAt','desc')),snap=>{S.reviews=snap.docs.map(d=>({id:d.id,...d.data()}));E.status.classList.add('hidden');render();renderProfile()})});
